# Generated by Django 4.0.6 on 2022-07-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBV', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
