# Generated by Django 3.2.12 on 2022-07-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBV', '0002_instructor_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Instructor',
            new_name='instructor',
        ),
    ]
